/**
 * @file src/constants/brand.ts
 * @desc Brand kit data for /brand: core color tokens (hex read from
 *       public/brand/haruhime-palette.json, generated by @haruhimemoe/brand and kept in sync with
 *       the @haruhimemoe/ui theme by a test), and the downloadable logo and README banner files in
 *       public/brand.
 * @author David @dvhsh (https://dvh.sh)
 * @created Wed Sep 23, 2026
 * @modified Wed Sep 23, 2026
 */

import palette from "../../public/brand/haruhime-palette.json" with { type: "json" };

/** Swatches shown on /brand, hex sourced from the generated haruhime-palette.json. */
export const BRAND_COLORS = [
  { token: "b6", name: "Background", hsl: [palette.hue, 10, 10], hex: palette.colors.b6 },
  { token: "b4", name: "Surface", hsl: [palette.hue, 10, 20], hex: palette.colors.b4 },
  { token: "c1", name: "Text", hsl: [palette.hue, 40, 100], hex: palette.colors.c1 },
  { token: "c3", name: "Muted text", hsl: [palette.hue, 40, 80], hex: palette.colors.c3 },
  { token: "h1", name: "Pink", hsl: [palette.hue, 100, 70], hex: palette.colors.h1 },
  { token: "h2", name: "Deep pink", hsl: [palette.hue, 50, 45], hex: palette.colors.h2 },
] as const;

/** Downloadable logo files generated by @haruhimemoe/brand, shown on /brand. */
export const BRAND_ASSETS = [
  {
    href: "brand/haruhime-wordmark.svg",
    label: "wordmark for dark backgrounds",
    background: "dark",
  },
  {
    href: "brand/haruhime-wordmark-on-light.svg",
    label: "wordmark for light backgrounds",
    background: "light",
  },
  { href: "brand/haruhime-icon.svg", label: "icon", background: "dark" },
] as const;

/**
 * README banners generated by @haruhimemoe/brand, shown on /brand: the dark one (as SVG and PNG)
 * and the light one.
 */
export const BRAND_BANNERS = [
  {
    preview: "brand/haruhime-banner.svg",
    downloads: [
      { href: "brand/haruhime-banner.svg", label: "banner for dark backgrounds" },
      { href: "brand/haruhime-banner.png", label: "banner for dark backgrounds (PNG)" },
    ],
  },
  {
    preview: "brand/haruhime-banner-on-light.svg",
    downloads: [
      { href: "brand/haruhime-banner-on-light.svg", label: "banner for light backgrounds" },
    ],
  },
] as const;

/** The README banner's size in pixels (the PNG's size and the SVGs' viewBox). */
export const BANNER_SIZE = { width: 1280, height: 320 } as const;

/** The stacked wordmark's viewBox size, so <img> tags reserve the right box before it loads. */
export const WORDMARK_SIZE = { width: 4447, height: 1179 } as const;
